{
 "title": "Minecraft Fleet",
 "tags": [
  "minecraft",
  "prometheus",
  "multi-host"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(mc_tps, job)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mc_tps{job=~\"$job\"}, instance)"
   },
   {
    "name": "world",
    "label": "World",
    "query": "label_values(mc_loaded_chunks_total{job=~\"$job\", instance=~\"$instance\"}, world)"
   },
   {
    "name": "entity_type",
    "label": "Entity Type",
    "query": "label_values(mc_entities_total{job=~\"$job\", instance=~\"$instance\", world=~\"$world\"}, type)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Players Online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mc_players_online_total{job=~\"$job\", instance=~\"$instance\", world=~\"$world\"})"
    }
   ]
  },
  {
   "title": "Known Players",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mc_players_total{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "JVM Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum by(instance) (mc_jvm_memory{type=\"allocated\", job=~\"$job\", instance=~\"$instance\"}) - sum by(instance) (mc_jvm_memory{type=\"free\", job=~\"$job\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Avg TPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(mc_tps{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Entities by Type",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, world, type) (mc_entities_total{job=~\"$job\", instance=~\"$instance\", world=~\"$world\", type=~\"$entity_type\"})",
     "legendFormat": "{{instance}} / {{world}} / {{type}}"
    }
   ]
  },
  {
   "title": "Players",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (mc_players_total{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Known {{instance}}"
    },
    {
     "expr": "sum by (instance, world) (mc_players_online_total{job=~\"$job\", instance=~\"$instance\", world=~\"$world\"})",
     "legendFormat": "Online {{instance}} / {{world}}"
    }
   ]
  },
  {
   "title": "Tickrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mc_tps{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "World Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, world) (mc_world_size{job=~\"$job\", instance=~\"$instance\", world=~\"$world\"})",
     "legendFormat": "{{instance}} / {{world}}"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, world) (mc_entities_total{job=~\"$job\", instance=~\"$instance\", world=~\"$world\"})",
     "legendFormat": "{{instance}} / {{world}}"
    }
   ]
  },
  {
   "title": "Villagers",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance, world, level, profession) (mc_villagers_total{job=~\"$job\", instance=~\"$instance\", world=~\"$world\"})",
     "legendFormat": "{{instance}} / {{world}} / {{profession}} (lv{{level}})"
    }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, world) (mc_loaded_chunks_total{job=~\"$job\", instance=~\"$instance\", world=~\"$world\"})",
     "legendFormat": "{{instance}} / {{world}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mc_jvm_threads_current{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Threads by state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mc_jvm_threads_state{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} / {{state}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (mc_jvm_memory{type=\"max\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Max {{instance}}"
    },
    {
     "expr": "sum by (instance) (mc_jvm_memory{type=\"allocated\", job=~\"$job\", instance=~\"$instance\"}) - sum by (instance) (mc_jvm_memory{type=\"free\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Used {{instance}}"
    }
   ]
  }
 ]
}